### PR TITLE
Groups overlap

### PR DESCRIPTION
**Pull request by abhisheklolage**
Groups overlap functionality added, new tab in GUI for multiple select insertions. Deletion facility added. 
Lecture insertion checks are yet to be added.

### CODE REVIEW

**Comment by abhijit13** [comment]
Won't Merge. 

Having overlapping groups makes little sense without separating the Subjects and Groups Tables. Right now subject-group mapping is tightly related. They should be separated and one more table showing Subject-offerred-to-list-of-groups mapping should be created.

**Comment by abhisheklolage** [comment]
Yes, the Subject Group UI is to be modified yet. Creation of groups is to be made independently.

**Comment by abhijit13** [comment]
Problem is still NOT solved. You are not separating the concept of a group from "teacher-subject". This will require changes to the group tab.

**Comment by abhijit13** [comment]
please rebase.

**Comment by abhisheklolage** [comment]
I am closing this pull request as I have rebased and made another pull request with additional functionalities.

**Pull request closed without merging**
