### PR TITLE
Min max work load of teacher

### PR DESCRIPTION
**Pull request by TusharAgey**
This merge will close the issue #2.
Only the teacher's table is modified.

### CODE REVIEW

**Comment by abhijit13** [comment]
curiously,
a diff with master shows almost entire file deleted and added again. This may be because some formatting change. 

Can you run your changes on top of master again?

**Comment by TusharAgey** [comment]
😅yeah, I saw the same problem. So is 'running the changes on top of master' again the only solution?

**Comment by TusharAgey** [comment]
The project itself contains the CRLF fileformat .. So, what can be done now?
screen shot 2017-03-19 at 6 56 00 pm

**Comment by TusharAgey** [comment]
The plugin that we have forked from 'https://github.com/antrouss/UniTimetable' is written in Windows environment I guess.

The file that I have created:
Tushars-MacBook-Air:UniTimeTable tushar$ file groupsoverlappingFunctions.php 
groupsoverlappingFunctions.php: PHP script text, ASCII text, with very long lines

The cloned file:
Tushars-MacBook-Air:UniTimeTable tushar$ file UniTimetable.php 
UniTimetable.php: PHP script text, ASCII text, with very long lines, with CRLF line terminators

**Comment by abhijit13** [comment]
Perhaps when I cloned it on Linux, some conversions happened. Let's find a
way to handle this in platform independent fashion

**Comment by TusharAgey** [comment]
sure!

**Pull request closed without merging**
